export function apptSmmrDummyData() {
  return [
    {
      Description: 'MOD APPT Total',
      Result: 2930,
      Cell_Result: 'D4',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,appointment',
      Order: '1',
    },
    {
      Description: 'MOD APPT Deflected #',
      Result: 427,
      Cell_Result: 'E4',
      Percentage: 14.57,
      Cell_Percentage: 'F4',
      Tags: 'appointment summary,mod ivr,appointment',
      Order: '2',
    },
    {
      Description: 'MOD APPT To Agent #',
      Result: 2504,
      Cell_Result: 'G4',
      Percentage: 85.46,
      Cell_Percentage: 'H4',
      Tags: 'appointment summary,mod ivr,appointment',
      Order: '3',
    },
    {
      Description: 'MOD CNCL Total',
      Result: 289,
      Cell_Result: 'D5',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,cancel',
      Order: '4',
    },
    {
      Description: 'MOD CNCL Deflected #',
      Result: 75,
      Cell_Result: 'E5',
      Percentage: 29.95,
      Cell_Percentage: 'F5',
      Tags: 'appointment summary,mod ivr,cancel',
      Order: '5',
    },
    {
      Description: 'MOD CNCL To Agent #',
      Result: 214,
      Cell_Result: 'G5',
      Percentage: '0',
      Cell_Percentage: 'H5',
      Tags: 'appointment summary,mod ivr,cancel',
      Order: '6',
    },
    {
      Description: 'MOD RSCH Total',
      Result: '0',
      Cell_Result: 'D6',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,reschedule',
      Order: '7',
    },
    {
      Description: 'MOD RSCH Deflected #',
      Result: '0',
      Cell_Result: 'E6',
      Percentage: '0',
      Cell_Percentage: 'F6',
      Tags: 'appointment summary,mod ivr,reschedule',
      Order: '8',
    },
    {
      Description: 'MOD RSCH To Agent #',
      Result: '0',
      Cell_Result: 'G6',
      Percentage: '0',
      Cell_Percentage: 'H6',
      Tags: 'appointment summary,mod ivr,reschedule',
      Order: '9',
    },
    {
      Description: 'MOD CNFM Total',
      Result: '0',
      Cell_Result: 'D7',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,confirm',
      Order: '10',
    },
    {
      Description: 'MOD CNFM Deflected #',
      Result: '0',
      Cell_Result: 'E7',
      Percentage: '0',
      Cell_Percentage: 'F7',
      Tags: 'appointment summary,mod ivr,confirm',
      Order: '11',
    },
    {
      Description: 'MOD CNFM To Agent #',
      Result: '0',
      Cell_Result: 'G7',
      Percentage: '0',
      Cell_Percentage: 'H7',
      Tags: 'appointment summary,mod ivr,confirm',
      Order: '12',
    },
    {
      Description: 'MOD OTHR Total',
      Result: '0',
      Cell_Result: 'D8',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,other',
      Order: '13',
    },
    {
      Description: 'MOD OTHR Deflected #',
      Result: '0',
      Cell_Result: 'E8',
      Percentage: '0',
      Cell_Percentage: 'F8',
      Tags: 'appointment summary,mod ivr,other',
      Order: '14',
    },
    {
      Description: 'MOD OTHR To Agent #',
      Result: '0',
      Cell_Result: 'G8',
      Percentage: '0',
      Cell_Percentage: 'H8',
      Tags: 'appointment summary,mod ivr,other',
      Order: '15',
    },
    {
      Description: 'CON Migrated Traffic %',
      Result: '0',
      Cell_Result: 'I4',
      Percentage: '0',
      Cell_Percentage: 'I4',
      Tags: 'appointment summary,conversational ivr,migrated traffic',
      Order: '16',
    },
    {
      Description: 'CON APPT Total',
      Result: '0',
      Cell_Result: 'J4',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,appointment',
      Order: '17',
    },
    {
      Description: 'CON APPT Deflected #',
      Result: '0',
      Cell_Result: 'K4',
      Percentage: '0',
      Cell_Percentage: 'L4',
      Tags: 'appointment summary,conversational ivr,appointment',
      Order: '18',
    },
    {
      Description: 'CON APPT To Agent #',
      Result: '0',
      Cell_Result: 'M4',
      Percentage: '0',
      Cell_Percentage: 'N4',
      Tags: 'appointment summary,conversational ivr,appointment',
      Order: '19',
    },
    {
      Description: 'CON CNCL Total',
      Result: '0',
      Cell_Result: 'J5',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,cancel',
      Order: '20',
    },
    {
      Description: 'CON CNCL Deflected #',
      Result: '0',
      Cell_Result: 'K5',
      Percentage: '0',
      Cell_Percentage: 'L5',
      Tags: 'appointment summary,conversational ivr,cancel',
      Order: '21',
    },
    {
      Description: 'CON CNCL To Agent #',
      Result: '0',
      Cell_Result: 'M5',
      Percentage: '0',
      Cell_Percentage: 'N5',
      Tags: 'appointment summary,conversational ivr,cancel',
      Order: '22',
    },
    {
      Description: 'CON RSCH Total',
      Result: '0',
      Cell_Result: 'J6',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,reschedule',
      Order: '23',
    },
    {
      Description: 'CON RSCH Deflected #',
      Result: '0',
      Cell_Result: 'K6',
      Percentage: '0',
      Cell_Percentage: 'L6',
      Tags: 'appointment summary,conversational ivr,reschedule',
      Order: '24',
    },
    {
      Description: 'CON RSCH To Agent #',
      Result: '0',
      Cell_Result: 'M6',
      Percentage: '0',
      Cell_Percentage: 'N6',
      Tags: 'appointment summary,conversational ivr,reschedule',
      Order: '25',
    },
    {
      Description: 'CON CNFM Total',
      Result: 211,
      Cell_Result: 'J7',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,confirm',
      Order: 26,
    },
    {
      Description: 'CON CNFM Deflected #',
      Result: 201,
      Cell_Result: 'K7',
      Percentage: 95.26,
      Cell_Percentage: 'L7',
      Tags: 'appointment summary,conversational ivr,confirm',
      Order: 27,
    },
    {
      Description: 'CON CNFM To Agent #',
      Result: 10,
      Cell_Result: 'M7',
      Percentage: 4.74,
      Cell_Percentage: 'N7',
      Tags: 'appointment summary,conversational ivr,confirm',
      Order: 28,
    },
    {
      Description: 'CON APPT Total',
      Result: 2248,
      Cell_Result: 'J8',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,other',
      Order: 29,
    },
    {
      Description: 'CON APPT Deflected #',
      Result: 723,
      Cell_Result: 'K8',
      Percentage: 32.16,
      Cell_Percentage: 'L8',
      Tags: 'appointment summary,conversational ivr,other',
      Order: 30,
    },
    {
      Description: 'CON APPT To Agent #',
      Result: 1529,
      Cell_Result: 'M8',
      Percentage: 68.02,
      Cell_Percentage: 'N8',
      Tags: 'appointment summary,conversational ivr,other',
      Order: 31,
    },
    {
      Description: 'Missing records',
      Result: 6,
      Cell_Result: 'J9',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,missing records',
      Order: 32,
    },
  ];
}
