export function apptSmmrDummyData() {
  return [
    {
      Description: 'MOD APPT Total',
      Cell_Description: '',
      Result: 2294,
      Cell_Result: 'D4',
      Percentage: 100,
      Cell_Percentage: '',

      Tags: '',
      Order: 1,
    },
    {
      Cell_Percentage: 'F4',
      Cell_Result: 'E4',
      Description: 'MOD APPT Deflected #',
      Cell_Description: 'D4',
      Order: 2,
      Percentage: 16.17,
      Tags: '',
      Result: 371,
    },
    {
      Cell_Percentage: 'H4',
      Cell_Result: 'G4',
      Description: 'MOD APPT To Agent #',
      Cell_Description: 'D4',
      Order: 3,
      Percentage: 83.83,
      Tags: '',
      Result: 1923,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'D5',
      Description: 'MOD CNCL Total',
      Cell_Description: 'D4',
      Order: 4,
      Percentage: 100,
      Tags: '',
      Result: 236,
    },
    {
      Cell_Percentage: 'F5',
      Cell_Result: 'E5',
      Description: 'MOD CNCL Deflected #',
      Cell_Description: 'D4',
      Order: 5,
      Percentage: 21.19,
      Tags: '',
      Result: 50,
    },
    {
      Cell_Percentage: 'H5',
      Cell_Result: 'G5',
      Description: 'MOD CNCL To Agent #',
      Cell_Description: 'D4',
      Order: 6,
      Percentage: 78.81,
      Tags: '',
      Result: 186,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'D6',
      Description: 'MOD RSCH Total',
      Cell_Description: 'D4',
      Order: 7,
      Percentage: 100,
      Tags: '',
      Result: 61,
    },
    {
      Cell_Percentage: 'F6',
      Cell_Result: 'E6',
      Description: 'MOD RSCH Deflected #',
      Cell_Description: 'D4',
      Order: 8,
      Percentage: 57.38,
      Tags: '',
      Result: 35,
    },
    {
      Cell_Percentage: 'H6',
      Cell_Result: 'G6',
      Description: 'MOD RSCH To Agent #',
      Cell_Description: 'D4',
      Order: 9,
      Percentage: 42.62,
      Tags: '',
      Result: 26,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'D7',
      Description: 'MOD CNFM Total',
      Cell_Description: 'D4',
      Order: 10,
      Percentage: 100,
      Tags: '',
      Result: 19,
    },
    {
      Cell_Percentage: 'F7',
      Cell_Result: 'E7',
      Description: 'MOD CNFM Deflected #',
      Cell_Description: 'D4',
      Order: 11,
      Percentage: 21.05,
      Tags: '',
      Result: 4,
    },
    {
      Cell_Percentage: 'H7',
      Cell_Result: 'G7',
      Description: 'MOD CNFM To Agent #',
      Cell_Description: 'D4',
      Order: 12,
      Percentage: 78.95,
      Tags: '',
      Result: 15,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'D8',
      Description: 'MOD APPT Total',
      Cell_Description: 'D4',
      Order: 13,
      Percentage: 100,
      Tags: '',
      Result: 1978,
    },
    {
      Cell_Percentage: 'F8',
      Cell_Result: 'E8',
      Description: 'MOD APPT Deflected #',
      Cell_Description: 'D4',
      Order: 14,
      Percentage: 14.26,
      Tags: '',
      Result: 282,
    },
    {
      Cell_Percentage: 'H8',
      Cell_Result: 'G8',
      Description: 'MOD APPT To Agent #',
      Cell_Description: 'D4',
      Order: 15,
      Percentage: 85.74,
      Tags: '',
      Result: 1696,
    },
    {
      Cell_Percentage: 'I4',
      Cell_Result: 'I4',
      Description: 'CON Migrated Traffic %',
      Cell_Description: 'D4',
      Order: 16,
      Percentage: 58.61,
      Tags: '',
      Result: 'NA',
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'J4',
      Description: 'CON APPT Total',
      Cell_Description: 'D4',
      Order: 17,
      Percentage: 100,
      Tags: '',
      Result: 3248,
    },
    {
      Cell_Percentage: 'L4',
      Cell_Result: 'K4',
      Description: 'CON APPT Deflected #',
      Cell_Description: 'D4',
      Order: 18,
      Percentage: 49.51,
      Tags: '',
      Result: 1608,
    },
    {
      Cell_Percentage: 'N4',
      Cell_Result: 'M4',
      Description: 'CON APPT To Agent #',
      Cell_Description: 'D4',
      Order: 19,
      Percentage: 50.62,
      Tags: '',
      Result: 1644,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'J5',
      Description: 'CON CNCL Total',
      Cell_Description: 'D4',
      Order: 20,
      Percentage: 100,
      Tags: '',
      Result: 552,
    },
    {
      Cell_Percentage: 'L5',
      Cell_Result: 'K5',
      Description: 'CON CNCL Deflected #',
      Cell_Description: 'D4',
      Order: 21,
      Percentage: 91.3,
      Tags: '',
      Result: 504,
    },
    {
      Cell_Percentage: 'N5',
      Cell_Result: 'M5',
      Description: 'CON CNCL To Agent #',
      Cell_Description: 'D4',
      Order: 22,
      Percentage: 8.7,
      Tags: '',
      Result: 48,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'J6',
      Description: 'CON RSCH Total',
      Cell_Description: 'D4',
      Order: 23,
      Percentage: 100,
      Tags: '',
      Result: 240,
    },
    {
      Cell_Percentage: 'L6',
      Cell_Result: 'K6',
      Description: 'CON RSCH Deflected #',
      Cell_Description: 'D4',
      Order: 24,
      Percentage: 76.25,
      Tags: '',
      Result: 183,
    },
    {
      Cell_Percentage: 'N6',
      Cell_Result: 'M6',
      Description: 'CON RSCH To Agent #',
      Cell_Description: 'D4',
      Order: 25,
      Percentage: 23.75,
      Tags: '',
      Result: 57,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'J7',
      Description: 'CON CNFM Total',
      Cell_Description: 'D4',
      Order: 26,
      Percentage: 100,
      Tags: '',
      Result: 211,
    },
    {
      Cell_Percentage: 'L7',
      Cell_Result: 'K7',
      Description: 'CON CNFM Deflected #',
      Cell_Description: 'D4',
      Order: 27,
      Percentage: 95.26,
      Tags: '',
      Result: 201,
    },
    {
      Cell_Percentage: 'N7',
      Cell_Result: 'M7',
      Description: 'CON CNFM To Agent #',
      Cell_Description: 'D4',
      Order: 28,
      Percentage: 4.74,
      Tags: '',
      Result: 10,
    },
    {
      Cell_Percentage: '',
      Cell_Result: 'J8',
      Description: 'CON APPT Total',
      Cell_Description: 'D4',
      Order: 29,
      Percentage: 100,
      Tags: '',
      Result: 2248,
    },
    {
      Cell_Percentage: 'L8',
      Cell_Result: 'K8',
      Description: 'CON APPT Deflected #',
      Cell_Description: 'D4',
      Order: 30,
      Percentage: 32.16,
      Tags: '',
      Result: 723,
    },
    {
      Cell_Percentage: 'N8',
      Cell_Result: 'M8',
      Description: 'CON APPT To Agent #',
      Cell_Description: 'D4',
      Order: 31,
      Percentage: 68.02,
      Tags: '',
      Result: 1529,
    },
  ];
}
