export function apptSmmrDummyData() {
  return [
    {
      Description: 'MOD APPT Total',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'D4',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,appointment',
      Order: '1',
    },
    {
      Description: 'MOD APPT Deflected #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'N' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'E4',
      Percentage: '0',
      Cell_Percentage: 'F4',
      Tags: 'appointment summary,mod ivr,appointment',
      Order: '2',
    },
    {
      Description: 'MOD APPT To Agent #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'Y' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'G4',
      Percentage: '0',
      Cell_Percentage: 'H4',
      Tags: 'appointment summary,mod ivr,appointment',
      Order: '3',
    },
    {
      Description: 'MOD CNCL Total',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND i.POC LIKE '%Appointment%Cancel%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'D5',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,cancel',
      Order: '4',
    },
    {
      Description: 'MOD CNCL Deflected #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'N' AND i.POC LIKE '%Appointment%Cancel%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'E5',
      Percentage: '0',
      Cell_Percentage: 'F5',
      Tags: 'appointment summary,mod ivr,cancel',
      Order: '5',
    },
    {
      Description: 'MOD CNCL To Agent #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'Y' AND i.POC LIKE '%Appointment%Cancel%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'G5',
      Percentage: '0',
      Cell_Percentage: 'H5',
      Tags: 'appointment summary,mod ivr,cancel',
      Order: '6',
    },
    {
      Description: 'MOD RSCH Total',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND i.POC LIKE '%Appointment%Reschedule%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'D6',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,reschedule',
      Order: '7',
    },
    {
      Description: 'MOD RSCH Deflected #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'N' AND i.POC LIKE '%Appointment%Reschedule%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'E6',
      Percentage: '0',
      Cell_Percentage: 'F6',
      Tags: 'appointment summary,mod ivr,reschedule',
      Order: '8',
    },
    {
      Description: 'MOD RSCH To Agent #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'Y' AND i.POC LIKE '%Appointment%Reschedule%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'G6',
      Percentage: '0',
      Cell_Percentage: 'H6',
      Tags: 'appointment summary,mod ivr,reschedule',
      Order: '9',
    },
    {
      Description: 'MOD CNFM Total',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND i.POC LIKE '%Appointment%Confirm%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'D7',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,confirm',
      Order: '10',
    },
    {
      Description: 'MOD CNFM Deflected #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'N' AND i.POC LIKE '%Appointment%Confirm%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'E7',
      Percentage: '0',
      Cell_Percentage: 'F7',
      Tags: 'appointment summary,mod ivr,confirm',
      Order: '11',
    },
    {
      Description: 'MOD CNFM To Agent #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND trans = 'Y' AND i.POC LIKE '%Appointment%Confirm%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'G7',
      Percentage: '0',
      Cell_Percentage: 'H7',
      Tags: 'appointment summary,mod ivr,confirm',
      Order: '12',
    },
    {
      Description: 'MOD OTHR Total',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND i.poc NOT LIKE '%Appointment%Cancel%' AND i.poc NOT LIKE '%Appointment%Reschedule%' AND i.poc NOT LIKE '%Appointment%Confirm%' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'D8',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,mod ivr,other',
      Order: '13',
    },
    {
      Description: 'MOD OTHR Deflected #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND i.poc NOT LIKE '%Appointment%Cancel%' AND i.poc NOT LIKE '%Appointment%Reschedule%' AND i.poc NOT LIKE '%Appointment%Confirm%' AND i.trans = 'N' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'E8',
      Percentage: '0',
      Cell_Percentage: 'F8',
      Tags: 'appointment summary,mod ivr,other',
      Order: '14',
    },
    {
      Description: 'MOD OTHR To Agent #',
      Query:
        "WITH TOT_CALLS AS ( SELECT DISTINCT UCID FROM IVR_CALLFLOW.IVRCALLINFO i WHERE i.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i.POC LIKE '%Appointment%' AND APPSERVER LIKE '%mod%' AND i.poc NOT LIKE '%Appointment%Cancel%' AND i.poc NOT LIKE '%Appointment%Reschedule%' AND i.poc NOT LIKE '%Appointment%Confirm%' AND i.trans = 'Y' ) ,SIK_CALLS AS (SELECT t.ucid FROM IVR_CALLFLOW.IVRCALLINFO t WHERE t.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND t.POC LIKE '%Appointment%' AND t.APPSERVER LIKE '%mod%' AND t.ucid IN (SELECT i2.ucid FROM IVR_CALLFLOW.IVRTRANDATA i2 WHERE i2.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND i2.KEY in ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') AND i2.value IN ('Eligible','SIK_INTERCEPT_ELIGIBLE')) ) ,NO_CHECK AS ( SELECT CAST(UCID AS varchar(100)) AS UCID, KEY, ROW_NUMBER() OVER (PARTITION BY UCID ORDER BY KEYSORT ASC) AS SEQ FROM ( SELECT T.*, CASE WHEN \"KEY\" IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') THEN callstop - 1 ELSE callstop END AS KEYSORT FROM IVR_CALLFLOW.ivrtrandata T WHERE ucid IN (SELECT ucid FROM TOT_CALLS) AND CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') )) SELECT count(DISTINCT ucid) FROM ( SELECT DISTINCT UCID FROM TOT_CALLS MINUS SELECT DISTINCT UCID FROM NO_CHECK WHERE SEQ = 1 AND \"KEY\" NOT IN ('Appointment_BOT_Eligibility_Reason','Appointment_Bot_Eligibility_Reason') MINUS SELECT DISTINCT ucid FROM SIK_CALLS )",
      Result: '0',
      Cell_Result: 'G8',
      Percentage: '0',
      Cell_Percentage: 'H8',
      Tags: 'appointment summary,mod ivr,other',
      Order: '15',
    },
    {
      Description: 'CON Migrated Traffic %',
      Query: 'NA',
      Result: '0',
      Cell_Result: 'I4',
      Percentage: '0',
      Cell_Percentage: 'I4',
      Tags: 'appointment summary,conversational ivr,migrated traffic',
      Order: '16',
    },
    {
      Description: 'CON APPT Total',
      Query:
        "SELECT count(DISTINCT ucid) FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'J4',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,appointment',
      Order: '17',
    },
    {
      Description: 'CON APPT Deflected #',
      Query:
        "SELECT count(DISTINCT ucid) FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.trans = 'N' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'K4',
      Percentage: '0',
      Cell_Percentage: 'L4',
      Tags: 'appointment summary,conversational ivr,appointment',
      Order: '18',
    },
    {
      Description: 'CON APPT To Agent #',
      Query:
        "SELECT count(DISTINCT ucid) AS cnt FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.TRANS = 'Y' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'M4',
      Percentage: '0',
      Cell_Percentage: 'N4',
      Tags: 'appointment summary,conversational ivr,appointment',
      Order: '19',
    },
    {
      Description: 'CON CNCL Total',
      Query:
        "SELECT sum(CASE WHEN c.poc IN ('Appointment_Intercept_Cancel','Appointment_Intercept_Cancel_Success','Appointment_Intercept_Cancel_Fail') THEN 1 ELSE 0 END) cancel_total FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.poc LIKE '%Cancel%' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'J5',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,cancel',
      Order: '20',
    },
    {
      Description: 'CON CNCL Deflected #',
      Query:
        "SELECT sum(CASE WHEN c.poc IN ('Appointment_Intercept_Cancel_Success','Appointment_Intercept_Cancel','Appointment_Intercept_Cancel_Fail') THEN 1 ELSE 0 END) cancel_deflected_calls FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.poc LIKE '%Cancel%' AND c.trans = 'N' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'K5',
      Percentage: '0',
      Cell_Percentage: 'L5',
      Tags: 'appointment summary,conversational ivr,cancel',
      Order: '21',
    },
    {
      Description: 'CON CNCL To Agent #',
      Query:
        "SELECT sum(CASE WHEN c.poc IN ('Appointment_Intercept_Cancel_Success','Appointment_Intercept_Cancel','Appointment_Intercept_Cancel_Fail') THEN 1 ELSE 0 END) cancel_deflected_calls FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.poc LIKE '%Cancel%' AND c.trans = 'Y' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'M5',
      Percentage: '0',
      Cell_Percentage: 'N5',
      Tags: 'appointment summary,conversational ivr,cancel',
      Order: '22',
    },
    {
      Description: 'CON RSCH Total',
      Query:
        "SELECT sum(CASE WHEN c.poc LIKE '%Reschedule%' AND c.poc NOT LIKE '%Reschedule_Ineligible' THEN 1 ELSE 0 END) rschl_total FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.poc LIKE '%Reschedule%' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'J6',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,reschedule',
      Order: '23',
    },
    {
      Description: 'CON RSCH Deflected #',
      Query:
        "SELECT sum(CASE WHEN c.poc LIKE '%Reschedule%' AND c.poc NOT LIKE '%Reschedule_Ineligible' THEN 1 ELSE 0 END) rschl_app_deflected FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.poc LIKE '%Reschedule%' AND c.TRANS = 'N' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'K6',
      Percentage: '0',
      Cell_Percentage: 'L6',
      Tags: 'appointment summary,conversational ivr,reschedule',
      Order: '24',
    },
    {
      Description: 'CON RSCH To Agent #',
      Query:
        "SELECT sum(CASE WHEN c.poc LIKE '%Reschedule%' AND c.poc NOT LIKE '%Reschedule_Ineligible' THEN 1 ELSE 0 END) rschl_app_to_agent FROM Kore.CALLINFO c WHERE c.CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND c.poc LIKE '%Reschedule%' AND c.TRANS = 'Y' AND ucid IN (SELECT DISTINCT ucid FROM IVR_CALLFLOW.IVRCALLINFO i WHERE CALLSTOP BETWEEN TO_DATE('dateStart 00:00:00', 'YYYY-MM-DD hh24:mi:ss') AND TO_DATE('dateEnd 23:59:59', 'YYYY-MM-DD hh24:mi:ss') AND category IN ('142','143'))",
      Result: '0',
      Cell_Result: 'M6',
      Percentage: '0',
      Cell_Percentage: 'N6',
      Tags: 'appointment summary,conversational ivr,reschedule',
      Order: '25',
    },
    {
      Description: 'CON CNFM Total',
      Result: 211,
      Cell_Result: 'J7',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,confirm',
      Order: 26,
    },
    {
      Description: 'CON CNFM Deflected #',
      Result: 201,
      Cell_Result: 'K7',
      Percentage: 95.26,
      Cell_Percentage: 'L7',
      Tags: 'appointment summary,conversational ivr,confirm',
      Order: 27,
    },
    {
      Description: 'CON CNFM To Agent #',
      Result: 10,
      Cell_Result: 'M7',
      Percentage: 4.74,
      Cell_Percentage: 'N7',
      Tags: 'appointment summary,conversational ivr,confirm',
      Order: 28,
    },
    {
      Description: 'CON APPT Total',
      Result: 2248,
      Cell_Result: 'J8',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,other',
      Order: 29,
    },
    {
      Description: 'CON APPT Deflected #',
      Result: 723,
      Cell_Result: 'K8',
      Percentage: 32.16,
      Cell_Percentage: 'L8',
      Tags: 'appointment summary,conversational ivr,other',
      Order: 30,
    },
    {
      Description: 'CON APPT To Agent #',
      Result: 1529,
      Cell_Result: 'M8',
      Percentage: 68.02,
      Cell_Percentage: 'N8',
      Tags: 'appointment summary,conversational ivr,other',
      Order: 31,
    },
    {
      Description: 'Missing records',
      Result: 6,
      Cell_Result: 'J9',
      Percentage: '100',
      Cell_Percentage: '',
      Tags: 'appointment summary,conversational ivr,missing records',
      Order: 32,
    },
  ];
}
