export function apptSmmrDummyData() {
  return [
    {
      'Cell_Percentage': '',
      'Cell_Result': 'D4',
      'Description': 'MOD APPT Total',
      'Order': 1,
      'Percentage': 100,
      'Result': 2294,
    },
    {
      'Cell_Percentage': 'F4',
      'Cell_Result': 'E4',
      'Description': 'MOD APPT Deflected #',
      'Order': 2,
      'Percentage': 16.17,
      'Result': 371,
    },
    {
      'Cell_Percentage': 'H4',
      'Cell_Result': 'G4',
      'Description': 'MOD APPT To Agent #',
      'Order': 3,
      'Percentage': 83.83,
      'Result': 1923,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'D5',
      'Description': 'MOD CNCL Total',
      'Order': 4,
      'Percentage': 100,
      'Result': 236,
    },
    {
      'Cell_Percentage': 'F5',
      'Cell_Result': 'E5',
      'Description': 'MOD CNCL Deflected #',
      'Order': 5,
      'Percentage': 21.19,
      'Result': 50,
    },
    {
      'Cell_Percentage': 'H5',
      'Cell_Result': 'G5',
      'Description': 'MOD CNCL To Agent #',
      'Order': 6,
      'Percentage': 78.81,
      'Result': 186,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'D6',
      'Description': 'MOD RSCH Total',
      'Order': 7,
      'Percentage': 100,
      'Result': 61,
    },
    {
      'Cell_Percentage': 'F6',
      'Cell_Result': 'E6',
      'Description': 'MOD RSCH Deflected #',
      'Order': 8,
      'Percentage': 57.38,
      'Result': 35,
    },
    {
      'Cell_Percentage': 'H6',
      'Cell_Result': 'G6',
      'Description': 'MOD RSCH To Agent #',
      'Order': 9,
      'Percentage': 42.62,
      'Result': 26,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'D7',
      'Description': 'MOD CNFM Total',
      'Order': 10,
      'Percentage': 100,
      'Result': 19,
    },
    {
      'Cell_Percentage': 'F7',
      'Cell_Result': 'E7',
      'Description': 'MOD CNFM Deflected #',
      'Order': 11,
      'Percentage': 21.05,
      'Result': 4,
    },
    {
      'Cell_Percentage': 'H7',
      'Cell_Result': 'G7',
      'Description': 'MOD CNFM To Agent #',
      'Order': 12,
      'Percentage': 78.95,
      'Result': 15,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'D8',
      'Description': 'MOD APPT Total',
      'Order': 13,
      'Percentage': 100,
      'Result': 1978,
    },
    {
      'Cell_Percentage': 'F8',
      'Cell_Result': 'E8',
      'Description': 'MOD APPT Deflected #',
      'Order': 14,
      'Percentage': 14.26,
      'Result': 282,
    },
    {
      'Cell_Percentage': 'H8',
      'Cell_Result': 'G8',
      'Description': 'MOD APPT To Agent #',
      'Order': 15,
      'Percentage': 85.74,
      'Result': 1696,
    },
    {
      'Cell_Percentage': 'I4',
      'Cell_Result': 'I4',
      'Description': 'CON Migrated Traffic %',
      'Order': 16,
      'Percentage': 58.61,
      'Result': 'NA',
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'J4',
      'Description': 'CON APPT Total',
      'Order': 17,
      'Percentage': 100,
      'Result': 3248,
    },
    {
      'Cell_Percentage': 'L4',
      'Cell_Result': 'K4',
      'Description': 'CON APPT Deflected #',
      'Order': 18,
      'Percentage': 49.51,
      'Result': 1608,
    },
    {
      'Cell_Percentage': 'N4',
      'Cell_Result': 'M4',
      'Description': 'CON APPT To Agent #',
      'Order': 19,
      'Percentage': 50.62,
      'Result': 1644,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'J5',
      'Description': 'CON CNCL Total',
      'Order': 20,
      'Percentage': 100,
      'Result': 552,
    },
    {
      'Cell_Percentage': 'L5',
      'Cell_Result': 'K5',
      'Description': 'CON CNCL Deflected #',
      'Order': 21,
      'Percentage': 91.3,
      'Result': 504,
    },
    {
      'Cell_Percentage': 'N5',
      'Cell_Result': 'M5',
      'Description': 'CON CNCL To Agent #',
      'Order': 22,
      'Percentage': 8.7,
      'Result': 48,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'J6',
      'Description': 'CON RSCH Total',
      'Order': 23,
      'Percentage': 100,
      'Result': 240,
    },
    {
      'Cell_Percentage': 'L6',
      'Cell_Result': 'K6',
      'Description': 'CON RSCH Deflected #',
      'Order': 24,
      'Percentage': 76.25,
      'Result': 183,
    },
    {
      'Cell_Percentage': 'N6',
      'Cell_Result': 'M6',
      'Description': 'CON RSCH To Agent #',
      'Order': 25,
      'Percentage': 23.75,
      'Result': 57,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'J7',
      'Description': 'CON CNFM Total',
      'Order': 26,
      'Percentage': 100,
      'Result': 211,
    },
    {
      'Cell_Percentage': 'L7',
      'Cell_Result': 'K7',
      'Description': 'CON CNFM Deflected #',
      'Order': 27,
      'Percentage': 95.26,
      'Result': 201,
    },
    {
      'Cell_Percentage': 'N7',
      'Cell_Result': 'M7',
      'Description': 'CON CNFM To Agent #',
      'Order': 28,
      'Percentage': 4.74,
      'Result': 10,
    },
    {
      'Cell_Percentage': '',
      'Cell_Result': 'J8',
      'Description': 'CON APPT Total',
      'Order': 29,
      'Percentage': 100,
      'Result': 2248,
    },
    {
      'Cell_Percentage': 'L8',
      'Cell_Result': 'K8',
      'Description': 'CON APPT Deflected #',
      'Order': 30,
      'Percentage': 32.16,
      'Result': 723,
    },
    {
      'Cell_Percentage': 'N8',
      'Cell_Result': 'M8',
      'Description': 'CON APPT To Agent #',
      'Order': 31,
      'Percentage': 68.02,
      'Result': 1529,
    },
  ];
}
