export function apptDtldDummyData() {
  return [
    {
      Description: 'Total Appointment Calls to MOD',
      Result: 4195,
      Cell_Result: 'B2',
      Percentage: '100',
      Cell_Percentage: 'C2',
      Intent: 'Summary',
      Order: 1,
    },
    {
      Description: 'Calls remained within MOD IVR (Not transferred to BOT)',
      Result: 1630,
      Cell_Result: 'B3',
      Percentage: 38.86,
      Cell_Percentage: 'C3',
      Intent: 'Summary',
      Order: 2,
    },
    {
      Description: 'Missing Records in BOT (Platform Bug)',
      Result: 0,
      Cell_Result: 'B4',
      Percentage: 0,
      Cell_Percentage: 'C4',
      Intent: 'Summary',
      Order: 3,
    },
    {
      Description: 'Total Appointment Calls from MOD to Bot',
      Result: 2566,
      Cell_Result: 'B5',
      Percentage: 61.17,
      Cell_Percentage: 'C5',
      Intent: 'Summary',
      Order: 4,
    },
    {
      Description: 'Transfers to BOT after Intercept',
      Result: 2450,
      Cell_Result: 'B6',
      Percentage: 95.48,
      Cell_Percentage: 'C6',
      Intent: 'Summary',
      Order: 5,
    },
    {
      Description: 'Transfers to BOT after MOD NLU',
      Result: 114,
      Cell_Result: 'B7',
      Percentage: 4.44,
      Cell_Percentage: 'C7',
      Intent: 'Summary',
      Order: 6,
    },
    {
      Description: 'Total Confirm Intent',
      Result: 2581,
      Cell_Result: 'B11',
      Percentage: '',
      Cell_Percentage: 'C11',
      Intent: 'Confirm',
      Order: 7,
    },
    {
      Description: 'Confirm Calls MOD Intercept (Proactive and Explicit)',
      Result: 'NA',
      Cell_Result: 'B12',
      Percentage: 'NA',
      Cell_Percentage: 'C12',
      Intent: 'Confirm',
      Order: 8,
    },
    {
      Description: 'Confirm Calls MOD NLU (Proactive and Explicit)',
      Result: 27,
      Cell_Result: 'B13',
      Percentage: '',
      Cell_Percentage: 'C13',
      Intent: 'Confirm',
      Order: 9,
    },
    {
      Description: 'Confirm Success (Proactive and Explicit)',
      Result: 2565,
      Cell_Result: 'B14',
      Percentage: '',
      Cell_Percentage: 'C14',
      Intent: 'Confirm',
      Order: 10,
    },
    {
      Description: 'Proactive Confirm Readout - Attempted',
      Result: 2566,
      Cell_Result: 'B15',
      Percentage: '',
      Cell_Percentage: 'C15',
      Intent: 'Confirm',
      Order: 11,
    },
    {
      Description: 'Proactive Confirm Readout - Success',
      Result: 2564,
      Cell_Result: 'B16',
      Percentage: 99.92,
      Cell_Percentage: 'C16',
      Intent: 'Confirm',
      Order: 12,
    },
    {
      Description: 'Proactive Confirm Readout - Failure',
      Result: 2,
      Cell_Result: 'B17',
      Percentage: 0.08,
      Cell_Percentage: 'C17',
      Intent: 'Confirm',
      Order: 13,
    },
    {
      Description: 'Proactive Confirm Readout - Transfer',
      Result: 0,
      Cell_Result: 'B18',
      Percentage: 0,
      Cell_Percentage: 'C18',
      Intent: 'Confirm',
      Order: 14,
    },
    {
      Description: 'Explicit Confirm Readout - Attempted',
      Result: 15,
      Cell_Result: 'B19',
      Percentage: '',
      Cell_Percentage: 'C19',
      Intent: 'Confirm',
      Order: 15,
    },
    {
      Description: 'Explicit Confirm Readout - Success',
      Result: 1,
      Cell_Result: 'B20',
      Percentage: 6.67,
      Cell_Percentage: 'C20',
      Intent: 'Confirm',
      Order: 16,
    },
    {
      Description: 'Explicit Confirm Readout - Failure',
      Result: 9,
      Cell_Result: 'B21',
      Percentage: 60,
      Cell_Percentage: 'C21',
      Intent: 'Confirm',
      Order: 17,
    },
    {
      Description: 'Explicit Confirm Readout - Transfer',
      Result: 5,
      Cell_Result: 'B22',
      Percentage: 33.33,
      Cell_Percentage: 'C22',
      Intent: 'Confirm',
      Order: 18,
    },
    {
      Description: 'Cancel Calls MOD Intercept',
      Result: 'NA',
      Cell_Result: 'B26',
      Percentage: 'NA',
      Cell_Percentage: 'C26',
      Intent: 'Cancel',
      Order: 19,
    },
    {
      Description: 'Cancel Calls MOD NLU',
      Result: 166,
      Cell_Result: 'B27',
      Percentage: '',
      Cell_Percentage: 'C27',
      Intent: 'Cancel',
      Order: 20,
    },
    {
      Description: 'Cancel -Attempted',
      Result: 1185,
      Cell_Result: 'B28',
      Percentage: '',
      Cell_Percentage: 'C28',
      Intent: 'Cancel',
      Order: 21,
    },
    {
      Description: 'Cancel - Success',
      Result: 1077,
      Cell_Result: 'B29',
      Percentage: 90.89,
      Cell_Percentage: 'C29',
      Intent: 'Cancel',
      Order: 22,
    },
    {
      Description: 'Cancel - Failure',
      Result: 11,
      Cell_Result: 'B30',
      Percentage: 0.93,
      Cell_Percentage: 'C30',
      Intent: 'Cancel',
      Order: 23,
    },
    {
      Description: 'Cancel - Transfer (Including Ineligible)',
      Result: 86,
      Cell_Result: 'B31',
      Percentage: 7.26,
      Cell_Percentage: 'C31',
      Intent: 'Cancel',
      Order: 24,
    },
    {
      Description: 'Cancel - Ineligible',
      Result: 56,
      Cell_Result: 'B32',
      Percentage: 4.73,
      Cell_Percentage: 'C32',
      Intent: 'Cancel',
      Order: 25,
    },
    {
      Description: 'Reschedule Calls MOD Intercept',
      Result: 'NA',
      Cell_Result: 'B35',
      Percentage: 'NA',
      Cell_Percentage: 'C35',
      Intent: 'Reschedule',
      Order: 26,
    },
    {
      Description: 'Reschedule Calls MOD NLU',
      Result: 24,
      Cell_Result: 'B36',
      Percentage: '',
      Cell_Percentage: 'C36',
      Intent: 'Reschedule',
      Order: 27,
    },
    {
      Description: 'Reschedule - Attempted',
      Result: 289,
      Cell_Result: 'B37',
      Percentage: '',
      Cell_Percentage: 'C37',
      Intent: 'Reschedule',
      Order: 28,
    },
    {
      Description: 'Reschedule - Success',
      Result: 240,
      Cell_Result: 'B38',
      Percentage: 83.04,
      Cell_Percentage: 'C38',
      Intent: 'Reschedule',
      Order: 29,
    },
    {
      Description: 'Reschedule - Failure',
      Result: 0,
      Cell_Result: 'B39',
      Percentage: 0,
      Cell_Percentage: 'C39',
      Intent: 'Reschedule',
      Order: 30,
    },
    {
      Description: 'Reschedule - Transfer (Including Ineligible)',
      Result: 49,
      Cell_Result: 'B40',
      Percentage: 16.96,
      Cell_Percentage: 'C40',
      Intent: 'Reschedule',
      Order: 31,
    },
    {
      Description: 'Reschedule - Ineligible',
      Result: 40,
      Cell_Result: 'B41',
      Percentage: 13.84,
      Cell_Percentage: 'C41',
      Intent: 'Reschedule',
      Order: 32,
    },
    {
      Description: 'Glympse Offer - Attempted',
      Result: 17,
      Cell_Result: 'B44',
      Percentage: '',
      Cell_Percentage: 'C44',
      Intent: 'Glympse',
      Order: 33,
    },
    {
      Description: 'Glympse Offer - Accepted',
      Result: 'NA',
      Cell_Result: 'B45',
      Percentage: 'NA',
      Cell_Percentage: 'C45',
      Intent: 'Glympse',
      Order: 34,
    },
    {
      Description: 'Glympse Offer - Failure',
      Result: 'NA',
      Cell_Result: 'B46',
      Percentage: 'NA',
      Cell_Percentage: 'C46',
      Intent: 'Glympse',
      Order: 35,
    },
    {
      Description: 'Glympse Offer - Not Accepted',
      Result: 'NA',
      Cell_Result: 'B47',
      Percentage: 'NA',
      Cell_Percentage: 'C47',
      Intent: 'Glympse',
      Order: 36,
    },
    {
      Description: 'Do I need to be at home ?',
      Result: 2,
      Cell_Result: 'B51',
      Percentage: 6.45,
      Cell_Percentage: 'C51',
      Intent: 'FAQ',
      Order: 37,
    },
    {
      Description: 'Is there any Fee for the appointment?',
      Result: 0,
      Cell_Result: 'B52',
      Percentage: 0,
      Cell_Percentage: 'C52',
      Intent: 'FAQ',
      Order: 38,
    },
    {
      Description: 'I have a missed call from spectrum ?',
      Result: 24,
      Cell_Result: 'B53',
      Percentage: 77.42,
      Cell_Percentage: 'C53',
      Intent: 'FAQ',
      Order: 39,
    },
    {
      Description: 'How long does it take to complete the work?',
      Result: 2,
      Cell_Result: 'B54',
      Percentage: 6.45,
      Cell_Percentage: 'C54',
      Intent: 'FAQ',
      Order: 40,
    },
    {
      Description:
        'How old does the person need to be to meet with the technician?',
      Result: 2,
      Cell_Result: 'B55',
      Percentage: 6.45,
      Cell_Percentage: 'C55',
      Intent: 'FAQ',
      Order: 41,
    },
    {
      Description: 'Do you call me before you start?',
      Result: 1,
      Cell_Result: 'B56',
      Percentage: 3.23,
      Cell_Percentage: 'C56',
      Intent: 'FAQ',
      Order: 42,
    },
    {
      Description: 'Can I manage my appointments online?',
      Cell_Description: 'A57',
      Result: 0,
      Cell_Result: 'B57',
      Percentage: 0,
      Cell_Percentage: 'C57',
      Intent: 'FAQ',
      Tags: 'appointment detailed,faq',
      Order: 43,
    },
    {
      Description: 'Total',
      Cell_Description: 'A58',
      Result: 31,
      Cell_Result: 'B58',
      Percentage: '100',
      Cell_Percentage: 'C58',
      Intent: 'FAQ',
      Tags: 'appointment detailed,faq',
      Order: 44,
    },
  ];
}
