export function apptDtldDummyData() {
  return [
    {
      'Description': 'Total Appointment Calls to MOD',
      'Result': 394739,
      'Cell_Result': 'B2',
      'Percentage': '100',
      'Cell_Percentage': 'C2',
      'Intent': 'Summary',
      'Order': 1,
    },
    {
      'Description': 'Calls remained within MOD IVR (Not transferred to BOT)',
      'Result': 168214,
      'Cell_Result': 'B3',
      'Percentage': 42.61,
      'Cell_Percentage': 'C3',
      'Intent': 'Summary',
      'Order': 2,
    },
    {
      'Description': 'Missing Records in BOT (Platform Bug)',
      'Result': 2354,
      'Cell_Result': 'B4',
      'Percentage': 0.6,
      'Cell_Percentage': 'C4',
      'Intent': 'Summary',
      'Order': 3,
    },
    {
      'Description': 'Total Appointment Calls from MOD to Bot',
      'Result': 224136,
      'Cell_Result': 'B5',
      'Percentage': 56.78,
      'Cell_Percentage': 'C5',
      'Intent': 'Summary',
      'Order': 4,
    },
    {
      'Description': 'Transfers to BOT after Intercept',
      'Result': 207496,
      'Cell_Result': 'B6',
      'Percentage': 92.58,
      'Cell_Percentage': 'C6',
      'Intent': 'Summary',
      'Order': 5,
    },
    {
      'Description': 'Transfers to BOT after MOD NLU',
      'Result': 9723,
      'Cell_Result': 'B7',
      'Percentage': 4.34,
      'Cell_Percentage': 'C7',
      'Intent': 'Summary',
      'Order': 6,
    },
    {
      'Description': 'Total Confirm Intent',
      'Result': 223920,
      'Cell_Result': 'B11',
      'Percentage': '',
      'Cell_Percentage': 'C11',
      'Intent': 'Confirm',
      'Order': 7,
    },
    {
      'Description': 'Confirm Calls MOD Intercept (Proactive and Explicit)',
      'Result': 'NA',
      'Cell_Result': 'B12',
      'Percentage': 'NA',
      'Cell_Percentage': 'C12',
      'Intent': 'Confirm',
      'Order': 8,
    },
    {
      'Description': 'Confirm Calls MOD NLU (Proactive and Explicit)',
      'Result': 4004,
      'Cell_Result': 'B13',
      'Percentage': '',
      'Cell_Percentage': 'C13',
      'Intent': 'Confirm',
      'Order': 9,
    },
    {
      'Description': 'Confirm Success (Proactive and Explicit)',
      'Result': 221663,
      'Cell_Result': 'B14',
      'Percentage': '',
      'Cell_Percentage': 'C14',
      'Intent': 'Confirm',
      'Order': 10,
    },
    {
      'Description': 'Proactive Confirm Readout - Attempted',
      'Result': 223489,
      'Cell_Result': 'B15',
      'Percentage': '',
      'Cell_Percentage': 'C15',
      'Intent': 'Confirm',
      'Order': 11,
    },
    {
      'Description': 'Proactive Confirm Readout - Success',
      'Result': 221641,
      'Cell_Result': 'B16',
      'Percentage': 99.17,
      'Cell_Percentage': 'C16',
      'Intent': 'Confirm',
      'Order': 12,
    },
    {
      'Description': 'Proactive Confirm Readout - Failure',
      'Result': 1847,
      'Cell_Result': 'B17',
      'Percentage': 0.83,
      'Cell_Percentage': 'C17',
      'Intent': 'Confirm',
      'Order': 13,
    },
    {
      'Description': 'Proactive Confirm Readout - Transfer',
      'Result': 1,
      'Cell_Result': 'B18',
      'Percentage': 0,
      'Cell_Percentage': 'C18',
      'Intent': 'Confirm',
      'Order': 14,
    },
    {
      'Description': 'Explicit Confirm Readout - Attempted',
      'Result': 431,
      'Cell_Result': 'B19',
      'Percentage': '',
      'Cell_Percentage': 'C19',
      'Intent': 'Confirm',
      'Order': 15,
    },
    {
      'Description': 'Explicit Confirm Readout - Success',
      'Result': 22,
      'Cell_Result': 'B20',
      'Percentage': 5.1,
      'Cell_Percentage': 'C20',
      'Intent': 'Confirm',
      'Order': 16,
    },
    {
      'Description': 'Explicit Confirm Readout - Failure',
      'Result': 102,
      'Cell_Result': 'B21',
      'Percentage': 23.67,
      'Cell_Percentage': 'C21',
      'Intent': 'Confirm',
      'Order': 17,
    },
    {
      'Description': 'Explicit Confirm Readout - Transfer',
      'Result': 305,
      'Cell_Result': 'B22',
      'Percentage': 70.77,
      'Cell_Percentage': 'C22',
      'Intent': 'Confirm',
      'Order': 18,
    },
    {
      'Description': 'Cancel Calls MOD Intercept',
      'Result': 'NA',
      'Cell_Result': 'B26',
      'Percentage': 'NA',
      'Cell_Percentage': 'C26',
      'Intent': 'Cancel',
      'Order': 19,
    },
    {
      'Description': 'Cancel Calls MOD NLU',
      'Result': 13230,
      'Cell_Result': 'B27',
      'Percentage': '',
      'Cell_Percentage': 'C27',
      'Intent': 'Cancel',
      'Order': 20,
    },
    {
      'Description': 'Cancel -Attempted',
      'Result': 74058,
      'Cell_Result': 'B28',
      'Percentage': '',
      'Cell_Percentage': 'C28',
      'Intent': 'Cancel',
      'Order': 21,
    },
    {
      'Description': 'Cancel - Success',
      'Result': 62521,
      'Cell_Result': 'B29',
      'Percentage': 84.42,
      'Cell_Percentage': 'C29',
      'Intent': 'Cancel',
      'Order': 22,
    },
    {
      'Description': 'Cancel - Failure',
      'Result': 1185,
      'Cell_Result': 'B30',
      'Percentage': 1.6,
      'Cell_Percentage': 'C30',
      'Intent': 'Cancel',
      'Order': 23,
    },
    {
      'Description': 'Cancel - Transfer (Including Ineligible)',
      'Result': 9824,
      'Cell_Result': 'B31',
      'Percentage': 13.27,
      'Cell_Percentage': 'C31',
      'Intent': 'Cancel',
      'Order': 24,
    },
    {
      'Description': 'Cancel - Ineligible',
      'Result': 7368,
      'Cell_Result': 'B32',
      'Percentage': 9.95,
      'Cell_Percentage': 'C32',
      'Intent': 'Cancel',
      'Order': 25,
    },
    {
      'Description': 'Reschedule Calls MOD Intercept',
      'Result': 'NA',
      'Cell_Result': 'B35',
      'Percentage': 'NA',
      'Cell_Percentage': 'C35',
      'Intent': 'Reschedule',
      'Order': 26,
    },
    {
      'Description': 'Reschedule Calls MOD NLU',
      'Result': 3518,
      'Cell_Result': 'B36',
      'Percentage': '',
      'Cell_Percentage': 'C36',
      'Intent': 'Reschedule',
      'Order': 27,
    },
    {
      'Description': 'Reschedule - Attempted',
      'Result': 29091,
      'Cell_Result': 'B37',
      'Percentage': '',
      'Cell_Percentage': 'C37',
      'Intent': 'Reschedule',
      'Order': 28,
    },
    {
      'Description': 'Reschedule - Success',
      'Result': 23802,
      'Cell_Result': 'B38',
      'Percentage': 81.82,
      'Cell_Percentage': 'C38',
      'Intent': 'Reschedule',
      'Order': 29,
    },
    {
      'Description': 'Reschedule - Failure',
      'Result': 11,
      'Cell_Result': 'B39',
      'Percentage': 0.04,
      'Cell_Percentage': 'C39',
      'Intent': 'Reschedule',
      'Order': 30,
    },
    {
      'Description': 'Reschedule - Transfer (Including Ineligible)',
      'Result': 5278,
      'Cell_Result': 'B40',
      'Percentage': 18.14,
      'Cell_Percentage': 'C40',
      'Intent': 'Reschedule',
      'Order': 31,
    },
    {
      'Description': 'Reschedule - Ineligible',
      'Result': 4809,
      'Cell_Result': 'B41',
      'Percentage': 16.53,
      'Cell_Percentage': 'C41',
      'Intent': 'Reschedule',
      'Order': 32,
    },
    {
      'Description': 'Glympse Offer - Attempted',
      'Result': 147,
      'Cell_Result': 'B44',
      'Percentage': '',
      'Cell_Percentage': 'C44',
      'Intent': 'Glympse',
      'Order': 33,
    },
    {
      'Description': 'Glympse Offer - Accepted',
      'Result': 'NA',
      'Cell_Result': 'B45',
      'Percentage': 'NA',
      'Cell_Percentage': 'C45',
      'Intent': 'Glympse',
      'Order': 34,
    },
    {
      'Description': 'Glympse Offer - Failure',
      'Result': 'NA',
      'Cell_Result': 'B46',
      'Percentage': 'NA',
      'Cell_Percentage': 'C46',
      'Intent': 'Glympse',
      'Order': 35,
    },
    {
      'Description': 'Glympse Offer - Not Accepted',
      'Result': 'NA',
      'Cell_Result': 'B47',
      'Percentage': 'NA',
      'Cell_Percentage': 'C47',
      'Intent': 'Glympse',
      'Order': 36,
    },
    {
      'Description': 'Do I need to be at home ?',
      'Result': 160,
      'Cell_Result': 'B51',
      'Percentage': 4.73,
      'Cell_Percentage': 'C51',
      'Intent': 'FAQ',
      'Order': 37,
    },
    {
      'Description': 'Is there any Fee for the appointment?',
      'Result': 109,
      'Cell_Result': 'B52',
      'Percentage': 3.22,
      'Cell_Percentage': 'C52',
      'Intent': 'FAQ',
      'Order': 38,
    },
    {
      'Description': 'I have a missed call from spectrum ?',
      'Result': 2559,
      'Cell_Result': 'B53',
      'Percentage': 75.67,
      'Cell_Percentage': 'C53',
      'Intent': 'FAQ',
      'Order': 39,
    },
    {
      'Description': 'How long does it take to complete the work?',
      'Result': 229,
      'Cell_Result': 'B54',
      'Percentage': 6.77,
      'Cell_Percentage': 'C54',
      'Intent': 'FAQ',
      'Order': 40,
    },
    {
      'Description':
        'How old does the person need to be to meet with the technician?',
      'Result': 160,
      'Cell_Result': 'B55',
      'Percentage': 4.73,
      'Cell_Percentage': 'C55',
      'Intent': 'FAQ',
      'Order': 41,
    },
    {
      'Description': 'Do you call me before you start?',
      'Result': 165,
      'Cell_Result': 'B56',
      'Percentage': 4.88,
      'Cell_Percentage': 'C56',
      'Intent': 'FAQ',
      'Order': 42,
    },
    {
      'Description': 'Can I manage my appointments online?',
      'Result': 0,
      'Cell_Result': 'B57',
      'Percentage': 0,
      'Cell_Percentage': 'C57',
      'Intent': 'FAQ',
      'Order': 43,
    },
    {
      'Description': 'Total',
      'Result': 3382,
      'Cell_Result': 'B58',
      'Percentage': '100',
      'Cell_Percentage': 'C58',
      'Intent': 'FAQ',
      'Order': 44,
    },
  ];
}
