export function billSmmrDummyData() {
  return [
    {
      Description: 'MOD BILL Total',
      Result: 2930,
      Cell_Result: 'D4',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,mod ivr,billing',
      Order: 1,
    },
    {
      Description: 'MOD BILL Deflected #',
      Result: 427,
      Cell_Result: 'E4',
      Percentage: 14.57,
      Cell_Percentage: 'F4',
      Tags: 'billing summary,mod ivr,billing',
      Order: 2,
    },
    {
      Description: 'MOD BILL To Agent #',
      Result: 2504,
      Cell_Result: 'G4',
      Percentage: 85.46,
      Cell_Percentage: 'H4',
      Tags: 'billing summary,mod ivr,billing',
      Order: 3,
    },
    {
      Description: 'MOD INCR Total',
      Result: 289,
      Cell_Result: 'D5',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,mod ivr,increase',
      Order: 4,
    },
    {
      Description: 'MOD INCR Deflected #',
      Result: 75,
      Cell_Result: 'E5',
      Percentage: 29.95,
      Cell_Percentage: 'F5',
      Tags: 'billing summary,mod ivr,increase',
      Order: 5,
    },
    {
      Description: 'MOD INCR To Agent #',
      Result: 214,
      Cell_Result: 'G5',
      Percentage: 74.05,
      Cell_Percentage: 'H5',
      Tags: 'billing summary,mod ivr,increase',
      Order: 6,
    },
    {
      Description: 'MOD QSTN Total',
      Result: 10,
      Cell_Result: 'D6',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,mod ivr,question',
      Order: 7,
    },
    {
      Description: 'MOD QSTN Deflected #',
      Result: 46,
      Cell_Result: 'E6',
      Percentage: 46,
      Cell_Percentage: 'F6',
      Tags: 'billing summary,mod ivr,question',
      Order: 8,
    },
    {
      Description: 'MOD QSTN To Agent #',
      Result: 54,
      Cell_Result: 'G6',
      Percentage: 54,
      Cell_Percentage: 'H6',
      Tags: 'billing summary,mod ivr,question',
      Order: 9,
    },
    {
      Description: 'MOD VGUE Total',
      Result: 27,
      Cell_Result: 'D7',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,mod ivr,vague',
      Order: 10,
    },
    {
      Description: 'MOD VGUE Deflected #',
      Result: 7,
      Cell_Result: 'E7',
      Percentage: 25.93,
      Cell_Percentage: 'F7',
      Tags: 'billing summary,mod ivr,vague',
      Order: 11,
    },
    {
      Description: 'MOD VGUE To Agent #',
      Result: 20,
      Cell_Result: 'G7',
      Percentage: 74.07,
      Cell_Percentage: 'H7',
      Tags: 'billing summary,mod ivr,vague',
      Order: 12,
    },
    {
      Description: 'MOD PMNT Total',
      Result: 2514,
      Cell_Result: 'D8',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,mod ivr,payment',
      Order: 13,
    },
    {
      Description: 'MOD PMNT Deflected #',
      Result: 299,
      Cell_Result: 'E8',
      Percentage: 11.89,
      Cell_Percentage: 'F8',
      Tags: 'billing summary,mod ivr,payment',
      Order: 14,
    },
    {
      Description: 'MOD PMNT To Agent #',
      Result: 2216,
      Cell_Result: 'G8',
      Percentage: 88.15,
      Cell_Percentage: 'H8',
      Tags: 'billing summary,mod ivr,payment',
      Order: 15,
    },
    {
      Description: 'MOD BLNC Total',
      Result: 184,
      Cell_Result: 'D9',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,mod ivr,balance',
      Order: 16,
    },
    {
      Description: 'MOD BLNC Deflected #',
      Result: 152,
      Cell_Result: 'E9',
      Percentage: 82.77,
      Cell_Percentage: 'F9',
      Tags: 'billing summary,mod ivr,balance',
      Order: 17,
    },
    {
      Description: 'MOD BLNC To Agent #',
      Result: 318,
      Cell_Result: 'G9',
      Percentage: 17.23,
      Cell_Percentage: 'H9',
      Tags: 'billing summary,mod ivr,balance',
      Order: 18,
    },
    {
      Description: 'MOD OTHR Total',
      Result: 3642,
      Cell_Result: 'D10',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,mod ivr,other',
      Order: 19,
    },
    {
      Description: 'MOD OTHR Deflected #',
      Result: 44,
      Cell_Result: 'E10',
      Percentage: 16,
      Cell_Percentage: 'F10',
      Tags: 'billing summary,mod ivr,other',
      Order: 20,
    },
    {
      Description: 'MOD OTHR To Agent #',
      Result: 356,
      Cell_Result: 'G10',
      Percentage: 84,
      Cell_Percentage: 'H10',
      Tags: 'billing summary,mod ivr,other',
      Order: 21,
    },
    {
      Description: 'CON Migrated Traffic %',
      Result: 'NA',
      Cell_Result: 'I4',
      Percentage: 56.65,
      Cell_Percentage: 'I4',
      Tags: 'billing summary,conversational ivr,migrated traffic',
      Order: 22,
    },
    {
      Description: 'CON BILL Total',
      Result: 3829,
      Cell_Result: 'J4',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,billing',
      Order: 23,
    },
    {
      Description: 'CON BILL Deflected #',
      Result: 1781,
      Cell_Result: 'K4',
      Percentage: 46.51,
      Cell_Percentage: 'L4',
      Tags: 'billing summary,conversational ivr,billing',
      Order: 24,
    },
    {
      Description: 'CON BILL To Agent #',
      Result: 2049,
      Cell_Result: 'M4',
      Percentage: 53.51,
      Cell_Percentage: 'N4',
      Tags: 'billing summary,conversational ivr,billing',
      Order: 25,
    },
    {
      Description: 'CON INCR Total',
      Result: 628,
      Cell_Result: 'J5',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,increase',
      Order: 26,
    },
    {
      Description: 'CON INCR Deflected #',
      Result: 566,
      Cell_Result: 'K5',
      Percentage: 90.13,
      Cell_Percentage: 'L5',
      Tags: 'billing summary,conversational ivr,increase',
      Order: 27,
    },
    {
      Description: 'CON INCR To Agent #',
      Result: 62,
      Cell_Result: 'M5',
      Percentage: 9.87,
      Cell_Percentage: 'N5',
      Tags: 'billing summary,conversational ivr,increase',
      Order: 28,
    },
    {
      Description: 'CON QSTN Total',
      Result: 327,
      Cell_Result: 'J6',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,question',
      Order: 29,
    },
    {
      Description: 'CON QSTN Deflected #',
      Result: 226,
      Cell_Result: 'K6',
      Percentage: 69.11,
      Cell_Percentage: 'L6',
      Tags: 'billing summary,conversational ivr,question',
      Order: 30,
    },
    {
      Description: 'CON QSTN To Agent #',
      Result: 101,
      Cell_Result: 'M6',
      Percentage: 30.89,
      Cell_Percentage: 'N6',
      Tags: 'billing summary,conversational ivr,question',
      Order: 31,
    },
    {
      Description: 'CON VGUE Total',
      Result: 1274,
      Cell_Result: 'J7',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,vague',
      Order: 32,
    },
    {
      Description: 'CON VGUE Deflected #',
      Result: 956,
      Cell_Result: 'K7',
      Percentage: 75.04,
      Cell_Percentage: 'L7',
      Tags: 'billing summary,conversational ivr,vague',
      Order: 33,
    },
    {
      Description: 'CON VGUE To Agent #',
      Result: 318,
      Cell_Result: 'M7',
      Percentage: 24.96,
      Cell_Percentage: 'N7',
      Tags: 'billing summary,conversational ivr,vague',
      Order: 34,
    },
    {
      Description: 'CON PMNT Total',
      Result: 1604,
      Cell_Result: 'J8',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,payment',
      Order: 35,
    },
    {
      Description: 'CON PMNT Deflected #',
      Result: 37,
      Cell_Result: 'K8',
      Percentage: 2.31,
      Cell_Percentage: 'L8',
      Tags: 'billing summary,conversational ivr,payment',
      Order: 36,
    },
    {
      Description: 'CON PMNT To Agent #',
      Result: 1568,
      Cell_Result: 'M8',
      Percentage: 97.76,
      Cell_Percentage: 'N8',
      Tags: 'billing summary,conversational ivr,payment',
      Order: 37,
    },
    {
      Description: 'CON BLNC Total',
      Result: 4235,
      Cell_Result: 'J9',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,balance',
      Order: 38,
    },
    {
      Description: 'CON BLNC Deflected #',
      Result: 2235,
      Cell_Result: 'K9',
      Percentage: 0,
      Cell_Percentage: 'L9',
      Tags: 'billing summary,conversational ivr,balance',
      Order: 39,
    },
    {
      Description: 'CON BLNC To Agent #',
      Result: 1800,
      Cell_Result: 'M9',
      Percentage: 0,
      Cell_Percentage: 'N9',
      Tags: 'billing summary,conversational ivr,balance',
      Order: 40,
    },
    {
      Description: 'CON OTHR Total',
      Result: 200,
      Cell_Result: 'J10',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,other',
      Order: 41,
    },
    {
      Description: 'CON OTHR Deflected #',
      Result: 150,
      Cell_Result: 'K10',
      Percentage: 75,
      Cell_Percentage: 'L10',
      Tags: 'billing summary,conversational ivr,other',
      Order: 42,
    },
    {
      Description: 'CON OTHR To Agent #',
      Result: 50,
      Cell_Result: 'M10',
      Percentage: 25,
      Cell_Percentage: 'N10',
      Tags: 'billing summary,conversational ivr,other',
      Order: 43,
    },
    {
      Description: 'Missing Records',
      Result: 21,
      Cell_Result: 'J11',
      Percentage: 100,
      Cell_Percentage: '',
      Tags: 'billing summary,conversational ivr,missing records',
      Order: 44,
    },
  ];
}
